package com.signal.common.exception;

public enum ErrorCode {
    DUPLICATE_LOGIN_ID,
    DUPLICATE_USER_CODE,
    INVALID_INPUT,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCOUNT_LOCKED,
    USER_NOT_FOUND,
    FRIENDSHIP_NOT_FOUND,
    FRIENDSHIP_ALREADY_EXISTS,
    FRIENDSHIP_INVALID_STATE,
    FRIENDSHIP_NOT_ACCEPTED,
    SELF_FRIENDSHIP,
    FORBIDDEN,
    CONVERSATION_NOT_FOUND,
    CONVERSATION_INACTIVE,
    NOT_MEMBER,
    DUPLICATE_MESSAGE_KEY,
    SYNC_CURSOR_CONFLICT,
    MESSAGE_NOT_FOUND
}
